# test_app
runtime: nodejs14
instance_class: F2
service: newtestapp

handlers:
 - url: /
   static_files: index.html
   upload: index.html

 - url: /api/.*
   secure: always
   redirect_http_response_code: 301
   script: auto
